package workspace

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/nataliagonzales81/oc-agent-workspace/internal/envelope"
	"github.com/nataliagonzales81/oc-agent-workspace/internal/yaml"
)

// Action is what init should do with one target file.
type Action string

const (
	// ActionCreate writes a file that does not exist.
	ActionCreate Action = "create"
	// ActionKeep leaves an existing file untouched and reports file_exists.
	ActionKeep Action = "keep"
	// ActionOverwrite replaces a file ocaw generated.
	ActionOverwrite Action = "overwrite"
	// ActionRefuse refuses a forced overwrite of a file ocaw did not write.
	ActionRefuse Action = "refuse"
)

// Target is the decision for one path, with the reasoning kept alongside it so
// the envelope can explain itself without the caller re-deriving any of it.
type Target struct {
	Path string `json:"path"`
	// Rel is the project-relative form, which is what a human wants to read.
	Rel string `json:"rel"`
	// Exists is true when the file was present before this decision.
	Exists bool `json:"exists"`
	// NonEmpty is true when the existing file has content.
	NonEmpty bool `json:"non_empty"`
	// Generated is true when the path is one `ocaw init` writes (§5).
	Generated bool   `json:"generated"`
	Action    Action `json:"action"`
	Reason    string `json:"reason"`
}

// OcawManifest reads agent.yaml. The `ocaw: true` marker it requires is the
// ownership record §5 refers to: a workspace that lacks it was assembled by a
// human, and ocaw does not claim it.
func (l *Layout) OcawManifest() (yaml.Agent, error) {
	raw, err := ReadFile(l.AgentYAML())
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return yaml.Agent{}, envelope.NewError(
				envelope.CodeWorkspaceMissing,
				fmt.Sprintf("no ocaw workspace at %s", l.Root),
				"ocaw init --dir "+l.Root,
			)
		}
		return yaml.Agent{}, err
	}
	agent, err := yaml.ParseAgent(string(raw))
	if err != nil {
		return yaml.Agent{}, envelope.Errorf(
			envelope.CodeValidationFailed,
			"ocaw doctor",
			"%s is not a readable ocaw manifest: %v", l.Rel(l.AgentYAML()), err,
		)
	}
	return agent, nil
}

// Managed reports whether the manifest carries the ocaw: true marker.
func (l *Layout) Managed() bool {
	ok, _ := l.managedState()
	return ok
}

// managedState answers whether ocaw owns this workspace, and says why not when
// it does not. The reason matters: "--force was refused" and "--force was
// refused because agent.yaml is not a manifest ocaw wrote" call for different
// fixes, so the reader's own complaint is carried through verbatim.
func (l *Layout) managedState() (bool, string) {
	_, err := l.OcawManifest()
	if err == nil {
		return true, ""
	}
	var envErr *envelope.Error
	if errors.As(err, &envErr) {
		if envErr.Code == envelope.CodeWorkspaceMissing {
			return false, "there is no agent.yaml"
		}
		return false, envErr.Message
	}
	return false, err.Error()
}

// Inspect decides what init should do with path.
//
// The rules are the spec's, in order:
//
//   - absent file → create, always;
//   - present but empty → overwrite, because there is nothing to lose;
//   - present with content and no --force → keep, reporting file_exists;
//   - present with content and --force → overwrite only if ocaw generated the
//     file *and* the workspace carries the ocaw: true marker. A skill, a
//     workflow packet, or any file a human added is refused, because --force
//     means "refresh what ocaw made", not "overwrite whatever is here".
func (l *Layout) Inspect(path string, force bool) (Target, error) {
	rel := l.Rel(path)
	t := Target{Path: path, Rel: rel, Generated: Generated(relPath(l.Root, path))}

	info, err := os.Stat(path)
	switch {
	case err == nil:
		t.Exists = true
		t.NonEmpty = info.Size() > 0
	case errors.Is(err, os.ErrNotExist):
		t.Action = ActionCreate
		t.Reason = "the file does not exist"
		return t, nil
	default:
		return t, envelope.Errorf(envelope.CodeInvalidPath, "check permissions on "+path, "cannot inspect %q: %v", rel, err)
	}

	if !t.NonEmpty {
		t.Action = ActionOverwrite
		t.Reason = "the existing file is empty"
		return t, nil
	}
	if !force {
		t.Action = ActionKeep
		t.Reason = "the file has content; pass --force to overwrite a file ocaw generated"
		return t, nil
	}
	managed, why := l.managedState()
	if !managed {
		t.Action = ActionRefuse
		t.Reason = "--force only overwrites files in a workspace ocaw manages, and " + why
		return t, nil
	}
	if !t.Generated {
		t.Action = ActionRefuse
		t.Reason = "--force only overwrites files ocaw generated, and this one was not generated by init"
		return t, nil
	}
	t.Action = ActionOverwrite
	t.Reason = "--force overwrites a file ocaw generated in a managed workspace"
	return t, nil
}

// InspectAll applies Inspect to a list of paths, in order.
func (l *Layout) InspectAll(paths []string, force bool) ([]Target, error) {
	out := make([]Target, 0, len(paths))
	for _, path := range paths {
		t, err := l.Inspect(path, force)
		if err != nil {
			return out, err
		}
		out = append(out, t)
	}
	return out, nil
}

// Refused returns the refused targets, which are the ones that make a forced
// run an error rather than a warning.
func Refused(targets []Target) []Target {
	var out []Target
	for _, t := range targets {
		if t.Action == ActionRefuse {
			out = append(out, t)
		}
	}
	return out
}

// Kept returns the targets left untouched, which are the ones that produce a
// file_exists warning.
func Kept(targets []Target) []Target {
	var out []Target
	for _, t := range targets {
		if t.Action == ActionKeep {
			out = append(out, t)
		}
	}
	return out
}

// relPath returns path relative to root when it is inside root, and the cleaned
// path otherwise. Generated compares project-relative paths, so a target
// outside the workspace can never claim to be generated.
func relPath(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil || len(rel) >= 2 && rel[0] == '.' && (rel[1] == '.' || rel[1] == filepath.Separator) {
		return filepath.Clean(path)
	}
	return rel
}
