package workspace

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/nataliagonzales81/oc-agent-workspace/internal/envelope"
)

func TestInspectAbsentFileCreates(t *testing.T) {
	l := managedLayout(t)
	got, err := l.Inspect(l.KnowledgeIndex(), false)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionCreate || got.Exists {
		t.Errorf("target = %+v, want a create", got)
	}
	if got.Rel != filepath.Join(AgentDir, "knowledge", "index.yaml") {
		t.Errorf("Rel = %q, want the project-relative path", got.Rel)
	}
}

// An existing but empty file has nothing to lose, so it is written even without
// --force. This keeps a half-finished init resumable.
func TestInspectEmptyFileOverwritesWithoutForce(t *testing.T) {
	l := newLayout(t)
	writeFile(t, l.RulesMD(), "")

	got, err := l.Inspect(l.RulesMD(), false)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionOverwrite {
		t.Errorf("action = %q, want %q", got.Action, ActionOverwrite)
	}
	if got.NonEmpty {
		t.Error("NonEmpty = true for a zero-byte file")
	}
}

func TestInspectNonEmptyFileKeepsWithoutForce(t *testing.T) {
	l := managedLayout(t)
	writeFile(t, l.RulesMD(), "my own rules\n")

	got, err := l.Inspect(l.RulesMD(), false)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionKeep {
		t.Errorf("action = %q, want %q", got.Action, ActionKeep)
	}
	if !strings.Contains(got.Reason, "--force") {
		t.Errorf("reason = %q, want it to name the flag that changes the answer", got.Reason)
	}
}

func TestInspectForceOverwritesAGeneratedFileInAManagedWorkspace(t *testing.T) {
	l := managedLayout(t)
	writeFile(t, l.RulesMD(), "stale placeholder\n")

	got, err := l.Inspect(l.RulesMD(), true)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionOverwrite {
		t.Errorf("action = %q, want %q (reason: %s)", got.Action, ActionOverwrite, got.Reason)
	}
	if !got.Generated {
		t.Error("Generated = false for a file init writes")
	}
}

func TestInspectForceRefusesANonGeneratedFile(t *testing.T) {
	l := managedLayout(t)
	skill := l.SkillFile("verify-first")
	writeFile(t, skill, "---\nname: verify-first\n---\nhand written\n")

	got, err := l.Inspect(skill, true)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionRefuse {
		t.Errorf("action = %q, want %q (reason: %s)", got.Action, ActionRefuse, got.Reason)
	}
	if !strings.Contains(got.Reason, "not generated by init") {
		t.Errorf("reason = %q, want it to say the file is not ocaw's", got.Reason)
	}
}

func TestInspectForceRefusesAnUnmanagedWorkspace(t *testing.T) {
	l := newLayout(t)
	writeManifest(t, l, false)
	writeFile(t, l.RulesMD(), "content\n")

	got, err := l.Inspect(l.RulesMD(), true)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionRefuse {
		t.Errorf("action = %q, want %q (reason: %s)", got.Action, ActionRefuse, got.Reason)
	}
	// `ocaw: false` is refused by the manifest reader itself, so the reason
	// carries the reader's own words rather than a paraphrase.
	if !strings.Contains(got.Reason, `"ocaw" must be true`) {
		t.Errorf("reason = %q, want it to carry the manifest reader's complaint", got.Reason)
	}
}

func TestInspectForceRefusesWhenThereIsNoManifest(t *testing.T) {
	l := newLayout(t)
	writeFile(t, l.RulesMD(), "content\n")

	got, err := l.Inspect(l.RulesMD(), true)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionRefuse {
		t.Errorf("action = %q, want %q (reason: %s)", got.Action, ActionRefuse, got.Reason)
	}
}

func TestInspectRefusesAPathOutsideTheWorkspace(t *testing.T) {
	l := managedLayout(t)
	outside := filepath.Join(t.TempDir(), "RULES.md")
	writeFile(t, outside, "not ours\n")

	got, err := l.Inspect(outside, true)
	if err != nil {
		t.Fatalf("Inspect: %v", err)
	}
	if got.Action != ActionRefuse {
		t.Errorf("action = %q, want %q: a file outside the root can never be ocaw's", got.Action, ActionRefuse)
	}
}

func TestInspectAllAndTheSelectionHelpers(t *testing.T) {
	l := managedLayout(t)
	writeFile(t, l.RulesMD(), "keep me\n")
	writeFile(t, l.SkillFile("s"), "keep me too\n")

	targets, err := l.InspectAll(l.Files(), false)
	if err != nil {
		t.Fatalf("InspectAll: %v", err)
	}
	if len(targets) != len(l.Files()) {
		t.Fatalf("got %d targets, want %d", len(targets), len(l.Files()))
	}
	kept := Kept(targets)
	if len(kept) != 2 {
		t.Fatalf("Kept = %+v, want agent.yaml and RULES.md", kept)
	}
	for _, want := range []string{l.AgentYAML(), l.RulesMD()} {
		found := false
		for _, k := range kept {
			if k.Path == want {
				found = true
			}
		}
		if !found {
			t.Errorf("Kept is missing %q", want)
		}
	}
	if len(Refused(targets)) != 0 {
		t.Errorf("Refused = %v, want none without --force", Refused(targets))
	}

	forced, err := l.InspectAll([]string{l.RulesMD(), l.SkillFile("s")}, true)
	if err != nil {
		t.Fatalf("InspectAll with force: %v", err)
	}
	refused := Refused(forced)
	if len(refused) != 1 || refused[0].Path != l.SkillFile("s") {
		t.Errorf("Refused = %+v, want just the skill file", refused)
	}
}

func TestOcawManifestRoundTrip(t *testing.T) {
	l := newLayout(t)
	writeManifest(t, l, true)
	agent, err := l.OcawManifest()
	if err != nil {
		t.Fatalf("OcawManifest: %v", err)
	}
	if !agent.Ocaw || agent.Name != "fixture" || agent.Project.Type != "go" {
		t.Errorf("agent = %+v", agent)
	}
}

func TestOcawManifestErrors(t *testing.T) {
	t.Run("missing", func(t *testing.T) {
		l := newLayout(t)
		if code := codeOf(t, mustErr(l.OcawManifest())); code != envelope.CodeWorkspaceMissing {
			t.Errorf("code = %s, want %s", code, envelope.CodeWorkspaceMissing)
		}
	})
	t.Run("garbage", func(t *testing.T) {
		l := newLayout(t)
		writeFile(t, l.AgentYAML(), "ocaw: true\n\tnope\n")
		if code := codeOf(t, mustErr(l.OcawManifest())); code != envelope.CodeValidationFailed {
			t.Errorf("code = %s, want %s", code, envelope.CodeValidationFailed)
		}
	})
	t.Run("wrong_schema", func(t *testing.T) {
		l := newLayout(t)
		writeFile(t, l.AgentYAML(), "ocaw: true\nschema: ocaw/agent@99\nname: x\nproject:\n  type: go\n")
		err := mustErr(l.OcawManifest())
		if codeOf(t, err) != envelope.CodeValidationFailed {
			t.Errorf("code = %s, want %s", codeOf(t, err), envelope.CodeValidationFailed)
		}
		if !strings.Contains(err.Error(), "ocaw/agent@1") {
			t.Errorf("error = %q, want it to name the schema this build writes", err)
		}
	})
}

func mustErr[T any](_ T, err error) error { return err }
